# Generated by Django 3.1.3 on 2020-12-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('products', models.ManyToManyField(to='records.Product')),
            ],
        ),
    ]
