# Generated by Django 3.1.3 on 2020-12-17 15:45

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=15),
        ),
    ]
